variable "org_name" {}
variable "api_token" {}
variable "base_url" {}
variable "demo_app_name" {}
variable "udp_subdomain" {}
variable "sleep" {
  default = 20

}
provider "okta" {
  org_name  = var.org_name
  api_token = var.api_token
  base_url  = var.base_url
  version   = "~> 3.0"
}
provider "local" {
  version = "~> 1.2"
}
data "okta_group" "all" {
  name = "Everyone"
}
resource "okta_group" "prospect" {
  name        = "Prospect"
  description = "(Generated by UDP)"
}
resource "okta_group" "customer" {
  name        = "Customer"
  description = "(Generated by UDP)"
}
resource "okta_app_oauth" "mlmDemoApp" {
  label          = "MLM Demo (Generated by UDP)"
  type           = "browser"
  grant_types    = ["implicit"]
  redirect_uris  = ["https://${var.udp_subdomain}.bod.unidemo.online/implicit/callback"]
  response_types = ["token", "id_token"]
  issuer_mode    = "ORG_URL"
  groups         = ["${data.okta_group.all.id}"]
  consent_method = "TRUSTED"
}
resource "okta_app_oauth" "mlmBlogApp" {
  label          = "MLM Blog-App (Generated by UDP)"
  type           = "browser"
  grant_types    = ["implicit"]
  redirect_uris  = ["https://${var.udp_subdomain}.bodblog.unidemo.live/implicit/callback"]
  response_types = ["token", "id_token"]
  issuer_mode    = "ORG_URL"
  groups         = ["${data.okta_group.all.id}"]
  consent_method = "TRUSTED"
}
resource "okta_auth_server" "bodUnidemo" {
  audiences   = ["api://bod.unidemo"]
  description = "bod"
  name        = "bod.unidemo"
}
resource "okta_auth_server_scope" "prospect" {
  description    = "prospect"
  name           = "prospect"
  auth_server_id = okta_auth_server.bodUnidemo.id
}
resource "okta_auth_server_scope" "customer" {
  description    = "customer"
  name           = "customer"
  auth_server_id = okta_auth_server.bodUnidemo.id
}
resource "null_resource" "delayAfterProspectScope" {
  provisioner "local-exec" {
    command = "sleep ${var.sleep}"
  }
  triggers = {
    before = okta_auth_server_scope.prospect.id
  }
}
resource "null_resource" "delayAfterCustomerScope" {
  provisioner "local-exec" {
    command = "sleep ${var.sleep}"
  }
  triggers = {
    before = okta_auth_server_scope.customer.id
  }
}
resource "okta_auth_server_claim" "groupsClaim" {
  name              = "groups"
  status            = "ACTIVE"
  claim_type        = "IDENTITY"
  value_type        = "GROUPS"
  group_filter_type = "REGEX"
  value             = ".*"
  auth_server_id    = okta_auth_server.bodUnidemo.id
}
resource "okta_auth_server_claim" "numFreebiesAvailableClaim" {
  name           = "numFreebiesAvailable"
  status         = "ACTIVE"
  claim_type     = "IDENTITY"
  value_type     = "EXPRESSION"
  value          = "user.numFreebiesAvailable"
  auth_server_id = okta_auth_server.bodUnidemo.id
}
resource "okta_auth_server_policy" "bodUnidemoDefaultPolicy" {
  status           = "ACTIVE"
  name             = "Default"
  description      = "Default"
  priority         = 1
  client_whitelist = ["ALL_CLIENTS"]
  auth_server_id   = okta_auth_server.bodUnidemo.id
}
resource "okta_auth_server_policy_rule" "bodUnidemoCustomerRule" {
  depends_on           = [null_resource.delayAfterCustomerScope]
  auth_server_id       = okta_auth_server.bodUnidemo.id
  policy_id            = okta_auth_server_policy.bodUnidemoDefaultPolicy.id
  status               = "ACTIVE"
  name                 = "Customer"
  priority             = 1
  group_whitelist      = ["${okta_group.customer.id}"]
  grant_type_whitelist = ["implicit"]
  scope_whitelist      = ["customer", "openid", "profile", "email"]
}
resource "okta_auth_server_policy_rule" "bodUnidemoProspectRule" {
  depends_on           = [null_resource.delayAfterProspectScope]
  auth_server_id       = okta_auth_server.bodUnidemo.id
  policy_id            = okta_auth_server_policy.bodUnidemoDefaultPolicy.id
  status               = "ACTIVE"
  name                 = "Prospect"
  priority             = 2
  group_whitelist      = ["${okta_group.prospect.id}"]
  grant_type_whitelist = ["implicit"]
  scope_whitelist      = ["prospect", "openid", "profile", "email"]
}
resource "okta_user_schema" "addWorkoutGoalsAttribute" {
  index  = "goals"
  title  = "Workout Goals"
  type   = "string"
  master = "PROFILE_MASTER"
}
resource "okta_user_schema" "addnumFreebiesAvailable" {
  index      = "numFreebiesAvailable"
  title      = "Number of previews available"
  type       = "number"
  master     = "PROFILE_MASTER"
  depends_on = [okta_user_schema.addWorkoutGoalsAttribute]
}
resource "okta_trusted_origin" "bodUnidemo" {
  name   = "${var.udp_subdomain}.bod.unidemo.online"
  origin = "https://${var.udp_subdomain}.bod.unidemo.online"
  scopes = ["CORS"]
}
resource "okta_trusted_origin" "bodBlogUnidemo" {
  name   = "${var.udp_subdomain}.bodblog.unidemo.live"
  origin = "https://${var.udp_subdomain}.bodblog.unidemo.live"
  scopes = ["CORS"]
}

output "client_id" {
  value = "${okta_app_oauth.mlmDemoApp.client_id}"
}
output "client_secret" {
  value = "${okta_app_oauth.mlmDemoApp.client_secret}"
}
output "issuer" {
  value = "${okta_auth_server.bodUnidemo.issuer}"
}
output "prospect_group_id" {
  value = "${okta_group.prospect.id}"
}
output "customer_group_id" {
  value = "${okta_group.customer.id}"
}
output "client2_id" {
  value = "${okta_app_oauth.mlmBlogApp.client_id}"
}