variable "org_name" {}
variable "api_token" {}
variable "base_url" {}
variable "demo_app_name" {
  default = "bod"
}
variable "udp_subdomain" {
  default = "local"
}
variable "sleep" {
  default = 20
}
locals {
    app_domain = "${var.udp_subdomain}.${var.demo_app_name}.unidemo.online"
}
terraform {
  required_providers {
    okta = {
      source = "oktadeveloper/okta"
      version = "~> 3.6"
    }
    local = {
      version = "~> 1.2"
    }
  }
}
provider "okta" {
  org_name  = var.org_name
  api_token = var.api_token
  base_url  = var.base_url
}
provider "local" {
}
data "okta_group" "all" {
  name = "Everyone"
}
resource "okta_group" "prospect" {
  name        = "${var.udp_subdomain}_${var.demo_app_name}_Prospect"
  description = "(Generated by UDP)"
}
resource "okta_group" "customer" {
  name        = "${var.udp_subdomain}_${var.demo_app_name}_Customer"
  description = "(Generated by UDP)"
}
resource "okta_app_oauth" "mlmDemoApp" {
  label          = "${var.udp_subdomain} MLM Demo (Generated by UDP)"
  type           = "native"
  omit_secret    = true
  token_endpoint_auth_method = "none"
  grant_types    = ["authorization_code", "refresh_token"]
  redirect_uris  = ["https://${local.app_domain}/login/callback","http://localhost:8080/login/callback"]
  post_logout_redirect_uris = ["https://${local.app_domain}","http://localhost:8080"]
  login_uri      = "https://${local.app_domain}/login/callback"
  response_types = ["code"]
  issuer_mode    = "ORG_URL"
  groups         = [data.okta_group.all.id]
  consent_method = "TRUSTED"
}
resource "okta_auth_server" "bodUnidemo" {
  audiences   = ["api://${var.demo_app_name}.unidemo"]
  description = "Generated by UDP"
  name        = "${var.udp_subdomain} ${var.demo_app_name} (Generated by UDP)"
}
resource "okta_auth_server_scope" "prospect" {
  description    = "prospect"
  name           = "prospect"
  auth_server_id = okta_auth_server.bodUnidemo.id
}
resource "okta_auth_server_scope" "customer" {
  description    = "customer"
  name           = "customer"
  auth_server_id = okta_auth_server.bodUnidemo.id
}
resource "null_resource" "delayAfterProspectScope" {
  provisioner "local-exec" {
    command = "sleep ${var.sleep}"
  }
  triggers = {
    before = okta_auth_server_scope.prospect.id
  }
}
resource "null_resource" "delayAfterCustomerScope" {
  provisioner "local-exec" {
    command = "sleep ${var.sleep}"
  }
  triggers = {
    before = okta_auth_server_scope.customer.id
  }
}
resource "okta_auth_server_claim" "groupsClaim" {
  name              = "groups"
  status            = "ACTIVE"
  claim_type        = "IDENTITY"
  value_type        = "GROUPS"
  group_filter_type = "REGEX"
  value             = ".*"
  auth_server_id    = okta_auth_server.bodUnidemo.id
}
resource "okta_auth_server_claim" "groupsResourceClaim" {
  name              = "groups"
  status            = "ACTIVE"
  claim_type        = "RESOURCE"
  value_type        = "GROUPS"
  group_filter_type = "REGEX"
  value             = ".*"
  auth_server_id    = okta_auth_server.bodUnidemo.id
}
resource "okta_auth_server_claim" "numFreebiesAvailableClaim" {
  name           = "numFreebiesAvailable"
  status         = "ACTIVE"
  claim_type     = "IDENTITY"
  value_type     = "EXPRESSION"
  value          = "user.numFreebiesAvailable"
  auth_server_id = okta_auth_server.bodUnidemo.id
}
resource "okta_auth_server_claim" "numFreebiesAvailableResourceClaim" {
  name           = "numFreebiesAvailable"
  status         = "ACTIVE"
  claim_type     = "RESOURCE"
  value_type     = "EXPRESSION"
  value          = "user.numFreebiesAvailable"
  auth_server_id = okta_auth_server.bodUnidemo.id
}
resource "okta_auth_server_claim" "stripeCustomerIdClaim" {
  name           = "stripeCustomerId"
  status         = "ACTIVE"
  claim_type     = "IDENTITY"
  value_type     = "EXPRESSION"
  value          = "user.stripeCustomerId"
  auth_server_id = okta_auth_server.bodUnidemo.id
}
resource "okta_auth_server_claim" "stripeCustomerIdResourceClaim" {
  name           = "stripeCustomerId"
  status         = "ACTIVE"
  claim_type     = "RESOURCE"
  value_type     = "EXPRESSION"
  value          = "user.stripeCustomerId"
  auth_server_id = okta_auth_server.bodUnidemo.id
}
resource "okta_auth_server_claim" "goalsClaim" {
  name           = "goals"
  status         = "ACTIVE"
  claim_type     = "IDENTITY"
  value_type     = "EXPRESSION"
  value          = "user.goals"
  auth_server_id = okta_auth_server.bodUnidemo.id
}
resource "okta_auth_server_claim" "goalsResourceClaim" {
  name           = "goals"
  status         = "ACTIVE"
  claim_type     = "RESOURCE"
  value_type     = "EXPRESSION"
  value          = "user.goals"
  auth_server_id = okta_auth_server.bodUnidemo.id
}
resource "okta_auth_server_policy" "bodUnidemoDefaultPolicy" {
  status           = "ACTIVE"
  name             = "Default"
  description      = "Default"
  priority         = 1
  client_whitelist = ["ALL_CLIENTS"]
  auth_server_id   = okta_auth_server.bodUnidemo.id
}
resource "okta_auth_server_policy_rule" "bodUnidemoCustomerRule" {
  depends_on           = [null_resource.delayAfterCustomerScope]
  auth_server_id       = okta_auth_server.bodUnidemo.id
  policy_id            = okta_auth_server_policy.bodUnidemoDefaultPolicy.id
  status               = "ACTIVE"
  name                 = "Customer"
  priority             = 1
  group_whitelist      = [okta_group.customer.id]
  grant_type_whitelist = ["authorization_code"]
  scope_whitelist      = ["customer", "openid", "profile", "email"]
}
resource "okta_auth_server_policy_rule" "bodUnidemoProspectRule" {
  depends_on           = [null_resource.delayAfterProspectScope]
  auth_server_id       = okta_auth_server.bodUnidemo.id
  policy_id            = okta_auth_server_policy.bodUnidemoDefaultPolicy.id
  status               = "ACTIVE"
  name                 = "Prospect"
  priority             = 2
  group_whitelist      = [okta_group.prospect.id]
  grant_type_whitelist = ["authorization_code"]
  scope_whitelist      = ["prospect", "openid", "profile", "email"]
}
resource "okta_user_schema" "addWorkoutGoalsAttribute" {
  index  = "goals"
  title  = "Workout Goals"
  type   = "string"
  master = "PROFILE_MASTER"
}
resource "okta_user_schema" "addnumFreebiesAvailable" {
  index      = "numFreebiesAvailable"
  title      = "Number of previews available"
  type       = "number"
  master     = "PROFILE_MASTER"
  depends_on = [okta_user_schema.addWorkoutGoalsAttribute]
}
resource "okta_user_schema" "stripeCustomerId" {
  index      = "stripeCustomerId"
  title      = "Stripe CustomerId"
  type       = "string"
  master     = "PROFILE_MASTER"
  depends_on = [okta_user_schema.addnumFreebiesAvailable]
}
resource "okta_trusted_origin" "bodUnidemo" {
  name   = local.app_domain
  origin = "https://${local.app_domain}"
  scopes = ["CORS"]
}
resource "okta_trusted_origin" "bodBlogUnidemo" {
  name   = "${var.udp_subdomain}.bodblog.unidemo.live"
  origin = "https://${var.udp_subdomain}.bodblog.unidemo.live"
  scopes = ["CORS"]
}

output "client_id" {
  value = okta_app_oauth.mlmDemoApp.client_id
}
output "client_secret" {
  value = okta_app_oauth.mlmDemoApp.client_secret
}
output "issuer" {
  value = okta_auth_server.bodUnidemo.issuer
}
output "prospect_group_id" {
  value = okta_group.prospect.id
}
output "customer_group_id" {
  value = okta_group.customer.id
}